# docker-compose.yml
services:
  datascience:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        PYTHON_VER: ${PYTHON_VER:-3.10}
        ENV_NAME: ${ENV_NAME:-data_science_ft_bio_predictions}
        JAX_PREALLOCATE: ${XLA_PYTHON_CLIENT_PREALLOCATE:-true}
        JAX_MEM_FRAC: ${XLA_PYTHON_CLIENT_MEM_FRACTION:-0.95}
        JAX_ALLOCATOR: ${XLA_PYTHON_CLIENT_ALLOCATOR:-platform}
        JAX_PREALLOC_LIMIT: ${JAX_PREALLOCATION_SIZE_LIMIT_BYTES:-8589934592}

    image: "data_science_ft_bio_predictions-datascience:latest"
    # (Removed explicit container_name to avoid "already in use" conflicts.)

    # Enhanced restart policy to handle port conflicts
    restart: unless-stopped

    gpus: all

    env_file:
      - dev.env
      - .devcontainer/.env

    environment:
      - PYTHON_VER=${PYTHON_VER}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics,display
      - JAX_PLATFORM_NAME=${JAX_PLATFORM_NAME}
      - XLA_PYTHON_CLIENT_PREALLOCATE=${XLA_PYTHON_CLIENT_PREALLOCATE}
      - XLA_PYTHON_CLIENT_ALLOCATOR=${XLA_PYTHON_CLIENT_ALLOCATOR}
      - XLA_PYTHON_CLIENT_MEM_FRACTION=${XLA_PYTHON_CLIENT_MEM_FRACTION}
      - XLA_FLAGS=${XLA_FLAGS}
      - JAX_DISABLE_JIT=${JAX_DISABLE_JIT}
      - JAX_ENABLE_X64=${JAX_ENABLE_X64}
      - TF_FORCE_GPU_ALLOW_GROWTH=${TF_FORCE_GPU_ALLOW_GROWTH}
      - JAX_PREALLOCATION_SIZE_LIMIT_BYTES=${JAX_PREALLOCATION_SIZE_LIMIT_BYTES}

    volumes:
      - .:/workspace
      - container_venv:/workspace/.venv

    ports:
      # Enhanced port configuration with fallback options
      - "${HOST_JUPYTER_PORT:-8890}:8888"
      - "${HOST_TENSORBOARD_PORT:-6008}:6008"
      - "${HOST_EXPLAINER_PORT:-8050}:8050"
      - "${HOST_STREAMLIT_PORT:-8501}:8501"
      - "${HOST_MLFLOW_PORT:-5000}:5000"

    # Launch Jupyter Lab directly in /workspace with proper configuration
    command: >
      bash -c "
      echo '=== Docker Dev Template Container Starting ===' &&
      cd /workspace &&
      source /workspace/.venv/bin/activate &&
      echo 'Python version:' &&
      /workspace/.venv/bin/python --version &&
      echo \"Jupyter will be available at: http://localhost:${HOST_JUPYTER_PORT:-8890}\" &&
      jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root
                  --NotebookApp.token='' --NotebookApp.notebook_dir=/workspace
      "

    healthcheck:
      test: ["CMD", "/workspace/.venv/bin/python", "-c", "import sys; print('Python', sys.version)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

    # Enhanced labels for better debugging
    labels:
      - "com.docker.compose.project=data_science_ft_bio_predictions"
      - "com.docker.compose.service=datascience"
      - "description=AI/ML Development Environment with GPU Support"

volumes:
  container_venv:

