name: data_science_ft_bio_predictions
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy==1.23.5
  - pandas
  - scikit-learn=1.5.2        # Downgraded from 1.6.0
  - matplotlib
  - ipympl
  - seaborn
  - jupyter
  - ipykernel
  - pytest
  - black
  - flake8
  - mypy
  - omegaconf
  - xgboost
  - scikit-optimize
  - pip
  - ffmpeg
  - pyyaml
  - pip:
      - pretty_errors 
      - gdown
      - CatBoost
      - lightgbm
      - pyspark
      - mplbasketball
      - imbalanced-learn
      - optuna
      - mlflow
      - shap
      - plotly
      - python-dotenv
      - joblib
      - streamlit
      - git+https://github.com/ghadfield32/ml_preprocessor
      - databricks-sdk
      - invoke
      - tensorflow
      - keras
      - mitosheet
      - mito-ai
